name: Build and deploy nodejs app.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            cd /app
            git fetch --all
            git reset --hard origin/main
            cd /scripts
            chmod +x .deploy.sh
            .deploy.sh
